### ISSUE TITLE
error occurred when git commit

### ISSUE THREAD

**Issue by dbbbit** [octplane/fsevent-rust#5]
Used the [example](https://github.com/octplane/fsevent-rust/tree/master/examples ) code to watch a git repo,
It works just fine until i do `git commit` in the watched repo.

``` 
> cargo run --verbose
       Fresh libc v0.2.2
       Fresh bitflags v0.3.3
       Fresh fsevent-sys v0.1.3
       Fresh fsevent v0.2.11
       Fresh dummy v0.1.0 (file:///Users/yangcheng/repos/dummy)
     Running `target/debug/dummy`
thread '<unnamed>' panicked at 'Unable to decode StreamFlags: 1115136', ../src/libcore/option.rs:333
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:736
Process didn't exit successfully: `target/debug/dummy` (exit code: 101)
```

**Comment by octplane** [comment]
Thanks for the bug report. Just released an update with the fix. Let me know if everything is ok for you now.

**Comment by dbbbit** [comment]
Works fine for me now, thanks~
